#!/bin/sh

CONFDIR=__MVC_RELOCATE____MVC_CATROOT__/config/cgi
CGIDIR=__MVC_CGIDIR__
CONFDIRFILES=__MVC_RELOCATE____MVC_CATROOT__/config/cgi/*

die() {
	echo $1
	exit 1
}

cd $CONFDIR || die "Cannot find $CONFDIR to change to.";

if [ "x`whoami`" = xroot ]
then
	ISROOT=1
else
	ISROOT=0
fi

if test -d $CGIDIR
then
	HASCGIDIR=1
else 
	die "Don't have cgidir $CGIDIR: $!"
fi

for f in $CONFDIRFILES
do
echo "testing f:$f"
	if test -f $CGIDIR/$f
	then
		echo "$f appears to be in cgi directory, skipping."
	else
		cp $f $CGIDIR || die "Cannot copy $f to $CGIDIR: $!"
		echo "$f has been copied to cgi dir $CGIDIR, remember to set proper ownership and permissions for proper function and security"
	fi
done

