#!/usr/local/bin/perl

	use CGI;
	use DBI;
	use Data::Dumper;

	my $q = new CGI;

	my $string = $q->param('q');

	### Set to 0 to go live
	my $indev = 0;

	my $ls = $q->param('limitStart') || 0;

	my $DSN = $indev ? 'dbi:mysql:test_bs30' : 'dbi:mysql:test_bs30';
	my $USER = '';
	my $PASS = '';

	my $ll = 20;
	my $next = $ls + $ll;
	my $prev = $ls - $ll;
	my $pmax = $prev + $ll;

	print $q->header();

#warn("ls:$ls ll:$ll\n");
	my $displayls = $ls + 1;

	my $limit = "$ls,$ll";
	if(length($string) > 1) {
		my $dbh = DBI->connect($DSN,$USER,$PASS) 
			or die ("No db handle!");

		### EDIT THESE TWO TO CHANGE
		my $mainq = "SELECT description FROM products WHERE inactive <> 1 and (description LIKE '%$string%') LIMIT $limit";
		my $maxq = "SELECT description FROM products WHERE inactive <> 1 and (description LIKE '%$string%')";

		my $ary = $dbh->selectall_arrayref($mainq);
#warn("string:$string query:$mainq");
		my $max = $dbh->do($maxq);
		$max > 0 or $max = 0;

#warn("returns:$max next:$next prev:$prev pmax:$pmax");
		$next = $max if $next > $max;

		my @out;
		if(@$ary){
			## DISPLAY, EDIT THESE
			push @out, "\n";

			foreach my $rec (@$ary) {

				my $line = <<EOF;
		<li onclick="fill('$rec->[0]');">$rec->[0]</li>
EOF
				push @out, "$line\n";
			}

			if($max > $next){
				my $more = <<EOF;
		<li onclick="lookup('$string', '$next');">NEXT >></li>
EOF
				push @out, "$more\n";
			}
			if($prev >= 0){
				my $prev_lnk = <<EOF;
		<li onclick="lookup('$string', '$prev');"><< PREVIOUS</li>
EOF
			push @out, "$prev_lnk\n";
			}

			print join '', @out;
		}
		else {
#			print "<li>Enter &nbsp;  <img src=/images/2012/MagnifyingGlass.png> &nbsp; to search everything for your term</li>";
			print "";
		}
	} 
	else {
		#do nothing
	}

